-- FLT CSR App — Supabase (PostgreSQL) schema
-- Equivalent to schema/sqlite_schema.sql for use in Supabase SQL Editor.

BEGIN;

-- Drop existing objects (safe re-run for fresh migration)
DROP TABLE IF EXISTS ticket_messages CASCADE;
DROP TABLE IF EXISTS ticket_status_logs CASCADE;
DROP TABLE IF EXISTS tickets CASCADE;
DROP TABLE IF EXISTS chat_messages CASCADE;
DROP TABLE IF EXISTS chat_assignment_events CASCADE;
DROP TABLE IF EXISTS chat_conversations CASCADE;
DROP TABLE IF EXISTS ticket_statuses CASCADE;
DROP TABLE IF EXISTS tech_team_accounts CASCADE;
DROP TABLE IF EXISTS admin_accounts CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(256) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    display_name VARCHAR(120),
    role VARCHAR(20) NOT NULL DEFAULT 'csr',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_available BOOLEAN NOT NULL DEFAULT TRUE,
    max_concurrent_chats INTEGER NOT NULL DEFAULT 4,
    last_assigned_at TIMESTAMP WITHOUT TIME ZONE,
    last_seen_at TIMESTAMP WITHOUT TIME ZONE,
    unlimited_chats BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX ix_users_role ON users (role);

CREATE TABLE admin_accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(256) NOT NULL,
    display_name VARCHAR(120),
    last_seen_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE
);
CREATE UNIQUE INDEX ix_admin_accounts_email ON admin_accounts (email);

CREATE TABLE tech_team_accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(256) NOT NULL,
    display_name VARCHAR(120),
    specialty VARCHAR(100) DEFAULT 'General',
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    last_seen_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE ticket_statuses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    label VARCHAR(100) NOT NULL,
    color VARCHAR(20) DEFAULT '#64748b',
    sort_order INTEGER DEFAULT 0,
    is_default BOOLEAN DEFAULT FALSE,
    is_resolved BOOLEAN DEFAULT FALSE
);

CREATE TABLE chat_conversations (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    external_chat_id VARCHAR(100) NOT NULL UNIQUE,
    customer_name VARCHAR(150) NOT NULL,
    customer_email VARCHAR(150),
    customer_external_user_id VARCHAR(120),
    auth_mode VARCHAR(20) NOT NULL DEFAULT 'anonymous',
    authenticated_user_data TEXT,
    subject VARCHAR(255),
    priority VARCHAR(20) NOT NULL DEFAULT 'normal',
    status VARCHAR(20) NOT NULL DEFAULT 'queued',
    source VARCHAR(40) NOT NULL DEFAULT 'qstp_widget',
    reverted_reason TEXT,
    last_customer_message TEXT,
    assigned_csr_id INTEGER REFERENCES users (id),
    assigned_at TIMESTAMP WITHOUT TIME ZONE,
    reverted_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    last_activity_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMP WITHOUT TIME ZONE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);
CREATE INDEX ix_chat_conversations_assigned_csr_id ON chat_conversations (assigned_csr_id);
CREATE INDEX ix_chat_conversations_status ON chat_conversations (status);
CREATE INDEX ix_chat_conversations_customer_external_user_id ON chat_conversations (customer_external_user_id);

CREATE TABLE chat_assignment_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id INTEGER NOT NULL REFERENCES chat_conversations (id) ON DELETE CASCADE,
    event_type VARCHAR(30) NOT NULL,
    from_csr_id INTEGER REFERENCES users (id),
    to_csr_id INTEGER REFERENCES users (id),
    acted_by_user_id INTEGER REFERENCES users (id),
    acted_by_name VARCHAR(120),
    acted_by_role VARCHAR(20),
    notes TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);
CREATE INDEX ix_chat_assignment_events_chat_id ON chat_assignment_events (chat_id);
CREATE INDEX ix_chat_assignment_events_event_type ON chat_assignment_events (event_type);

CREATE TABLE chat_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id INTEGER NOT NULL REFERENCES chat_conversations (id) ON DELETE CASCADE,
    sender_type VARCHAR(20) NOT NULL,
    content TEXT NOT NULL,
    image_attachments TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);
CREATE INDEX ix_chat_messages_sender_type ON chat_messages (sender_type);
CREATE INDEX ix_chat_messages_chat_id ON chat_messages (chat_id);

CREATE TABLE tickets (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_number VARCHAR(24) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    priority VARCHAR(20) NOT NULL DEFAULT 'normal',
    status VARCHAR(50) NOT NULL DEFAULT 'open',
    created_by_csr_id INTEGER NOT NULL REFERENCES users (id),
    chat_id INTEGER REFERENCES chat_conversations (id),
    assigned_tech_id INTEGER REFERENCES tech_team_accounts (id),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    resolved_at TIMESTAMP WITHOUT TIME ZONE
);
CREATE INDEX ix_tickets_assigned_tech_id ON tickets (assigned_tech_id);
CREATE INDEX ix_tickets_status ON tickets (status);
CREATE INDEX ix_tickets_chat_id ON tickets (chat_id);

CREATE TABLE ticket_status_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id INTEGER NOT NULL REFERENCES tickets (id) ON DELETE CASCADE,
    old_status VARCHAR(50),
    new_status VARCHAR(50) NOT NULL,
    old_assigned_tech_id INTEGER,
    new_assigned_tech_id INTEGER,
    changed_by_user_id INTEGER,
    changed_by_role VARCHAR(20),
    notes TEXT,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);
CREATE INDEX ix_ticket_status_logs_ticket_id ON ticket_status_logs (ticket_id);

CREATE TABLE ticket_messages (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id INTEGER NOT NULL REFERENCES tickets (id) ON DELETE CASCADE,
    sender_type VARCHAR(20) NOT NULL,
    sender_id INTEGER NOT NULL,
    sender_name VARCHAR(120),
    content TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);
CREATE INDEX ix_ticket_messages_sender_type ON ticket_messages (sender_type);
CREATE INDEX ix_ticket_messages_ticket_id ON ticket_messages (ticket_id);

COMMIT;
